# Generated by Django 2.2.11 on 2020-03-09 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('content', models.TextField(verbose_name='content')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
