# Generated by Django 2.2.11 on 2020-03-09 14:20

import config.settings.local
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'get_latest_by': '-date_created'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(storage=config.settings.local.PrivateS3Boto3Storage(), upload_to='', verbose_name='image'),
        ),
    ]
