# Generated by Django 2.2.11 on 2020-03-11 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0004_auto_20200309_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('startup', 'STARTUP'), ('life style', 'LIFE STYLE'), ('events', 'EVENTS'), ('technology jobs', 'TECHNOLOGY JOBS'), ('funding', 'FUNDING'), ('reviews and deals', 'REVIEWS AND DEALS'), ('technologies and gadgets', 'TECHNOLOGIES AND GADGETS')], max_length=200, null=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='published_by',
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_category', to='publications.PublicationCategory'),
        ),
        migrations.CreateModel(
            name='SponsoredPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsored', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_category', to='publications.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='publications.Publication')),
            ],
        ),
    ]
