# Generated by Django 2.2.11 on 2020-03-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20200311_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsoredpublication',
            name='sponsored',
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'get_latest_by': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='publication',
            name='featured_publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='publications.Publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='sponsored_publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored', to='publications.Publication'),
        ),
        migrations.DeleteModel(
            name='FeaturedPublication',
        ),
        migrations.DeleteModel(
            name='SponsoredPublication',
        ),
    ]
